// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Restoran.Data;

#nullable disable

namespace Restoran.Data.Migrations
{
    [DbContext(typeof(DbRestoranContext))]
    [Migration("20260722140403_MalzemeTalepEkle")]
    partial class MalzemeTalepEkle
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Restoran.Data.Entities.Adres", b =>
                {
                    b.Property<int>("AdresId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("AdresID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AdresId"));

                    b.Property<string>("AcikAdres")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AdresTipi")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool?>("TeslimatBolgesindeMi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int?>("UyeId")
                        .HasColumnType("int")
                        .HasColumnName("UyeID");

                    b.HasKey("AdresId")
                        .HasName("PK__Adres__DA8DEA6C0FC10825");

                    b.HasIndex("UyeId");

                    b.ToTable("Adres");
                });

            modelBuilder.Entity("Restoran.Data.Entities.Iade", b =>
                {
                    b.Property<int>("IadeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IadeID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IadeId"));

                    b.Property<string>("IadeDurumu")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("BEKLEMEDE");

                    b.Property<string>("IadeSebebi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("IadeTarihi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<decimal>("IadeTutari")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int?>("PersonelId")
                        .HasColumnType("int")
                        .HasColumnName("PersonelID");

                    b.Property<int?>("SiparisDetayId")
                        .HasColumnType("int")
                        .HasColumnName("SiparisDetayID");

                    b.Property<int?>("UrunId")
                        .HasColumnType("int")
                        .HasColumnName("UrunID");

                    b.HasKey("IadeId")
                        .HasName("PK__Iade__D047997FB4226E2E");

                    b.HasIndex("PersonelId");

                    b.HasIndex("SiparisDetayId");

                    b.HasIndex("UrunId");

                    b.ToTable("Iade", (string)null);
                });

            modelBuilder.Entity("Restoran.Data.Entities.Kasa", b =>
                {
                    b.Property<int>("KasaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("KasaID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KasaId"));

                    b.Property<decimal?>("AcilisBakiyesi")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<DateTime>("AcilisTarihi")
                        .HasColumnType("datetime");

                    b.Property<decimal?>("KapanisBakiyesi")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<DateTime?>("KapanisTarihi")
                        .HasColumnType("datetime");

                    b.Property<string>("KasaDurumu")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("PersonelId")
                        .HasColumnType("int")
                        .HasColumnName("PersonelID");

                    b.HasKey("KasaId")
                        .HasName("PK__Kasa__1595E41150A253EE");

                    b.HasIndex("PersonelId");

                    b.ToTable("Kasa", (string)null);
                });

            modelBuilder.Entity("Restoran.Data.Entities.Kategori", b =>
                {
                    b.Property<int>("KategoriId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("KategoriID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KategoriId"));

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("KategoriAdi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("SilinmeTarihi")
                        .HasColumnType("datetime2");

                    b.HasKey("KategoriId")
                        .HasName("PK__Kategori__1782CC926A0AF70B");

                    b.ToTable("Kategori", (string)null);
                });

            modelBuilder.Entity("Restoran.Data.Entities.MalzemeTalep", b =>
                {
                    b.Property<int>("TalepId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TalepId"));

                    b.Property<string>("Aciklama")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Birim")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("CevaplamaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("Cevaplayan")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Durum")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("MalzemeId")
                        .HasColumnType("int");

                    b.Property<int>("Miktar")
                        .HasColumnType("int");

                    b.Property<int?>("PersonelId")
                        .HasColumnType("int");

                    b.Property<string>("TalepEden")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("TalepTarihi")
                        .HasColumnType("datetime2");

                    b.HasKey("TalepId");

                    b.HasIndex("MalzemeId");

                    b.ToTable("MalzemeTalepleri");
                });

            modelBuilder.Entity("Restoran.Data.Entities.Malzemeler", b =>
                {
                    b.Property<int>("MalzemeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MalzemeID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MalzemeId"));

                    b.Property<string>("Birim")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal?>("BirimMaliyeti")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("MalzemeAdi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("StokMiktari")
                        .HasColumnType("decimal(10, 2)");

                    b.HasKey("MalzemeId")
                        .HasName("PK__Malzemel__4ED155E09E404CB7");

                    b.ToTable("Malzemeler", (string)null);
                });

            modelBuilder.Entity("Restoran.Data.Entities.Masa", b =>
                {
                    b.Property<int>("MasaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MasaID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MasaId"));

                    b.Property<string>("MasaDurumu")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("MasaNo")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("MasaId")
                        .HasName("PK__Masa__9F94EBD36A10F83C");

                    b.ToTable("Masa", (string)null);
                });

            modelBuilder.Entity("Restoran.Data.Entities.Odeme", b =>
                {
                    b.Property<int>("OdemeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("OdemeID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OdemeId"));

                    b.Property<int?>("KasaId")
                        .HasColumnType("int")
                        .HasColumnName("KasaID");

                    b.Property<DateTime?>("OdemeTarihi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("OdemeTipi")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("OdemeTutari")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int?>("PersonelId")
                        .HasColumnType("int")
                        .HasColumnName("PersonelID");

                    b.Property<int?>("SiparisId")
                        .HasColumnType("int")
                        .HasColumnName("SiparisID");

                    b.HasKey("OdemeId")
                        .HasName("PK__Odeme__B11B66AD0AE797C9");

                    b.HasIndex("KasaId");

                    b.HasIndex("PersonelId");

                    b.HasIndex("SiparisId");

                    b.ToTable("Odeme", (string)null);
                });

            modelBuilder.Entity("Restoran.Data.Entities.Personel", b =>
                {
                    b.Property<int>("PersonelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PersonelID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PersonelId"));

                    b.Property<string>("Cinsiyet")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateOnly?>("IseBaslamaTarihi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("KullaniciAdi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal?>("Maas")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("PersonelAdi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PersonelSifre")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("PersonelSoyadi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PersonelTelefon")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RefreshTokenBitis")
                        .HasColumnType("datetime2");

                    b.Property<int?>("RolId")
                        .HasColumnType("int")
                        .HasColumnName("RolID");

                    b.Property<DateTime?>("SilinmeTarihi")
                        .HasColumnType("datetime2");

                    b.HasKey("PersonelId")
                        .HasName("PK__Personel__0F0C5751E6FDDC9A");

                    b.HasIndex("RolId");

                    b.ToTable("Personel", (string)null);
                });

            modelBuilder.Entity("Restoran.Data.Entities.PersonelIzin", b =>
                {
                    b.Property<int>("IzinId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IzinID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IzinId"));

                    b.Property<string>("IzinAciklamasi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("IzinBaslangic")
                        .HasColumnType("date");

                    b.Property<DateOnly>("IzinBitis")
                        .HasColumnType("date");

                    b.Property<string>("IzinDurumu")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("BEKLEMEDE");

                    b.Property<int?>("PersonelId")
                        .HasColumnType("int")
                        .HasColumnName("PersonelID");

                    b.HasKey("IzinId")
                        .HasName("PK__Personel__4700791E92F85897");

                    b.HasIndex("PersonelId");

                    b.ToTable("PersonelIzin", (string)null);
                });

            modelBuilder.Entity("Restoran.Data.Entities.Rezervasyon", b =>
                {
                    b.Property<int>("RezervasyonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("RezervasyonID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RezervasyonId"));

                    b.Property<string>("Aciklama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Durum")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("BEKLEMEDE");

                    b.Property<int>("KisiSayisi")
                        .HasColumnType("int");

                    b.Property<int>("MasaId")
                        .HasColumnType("int")
                        .HasColumnName("MasaID");

                    b.Property<string>("MusteriAdi")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("MusteriSoyadi")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("OlusturulmaTarihi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("RezervasyonTipi")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("TarihSaat")
                        .HasColumnType("datetime");

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<int?>("UyeId")
                        .HasColumnType("int")
                        .HasColumnName("UyeID");

                    b.HasKey("RezervasyonId")
                        .HasName("PK__Rezervas__CD4DF9786785B85B");

                    b.HasIndex("MasaId");

                    b.HasIndex("UyeId");

                    b.ToTable("Rezervasyon", (string)null);
                });

            modelBuilder.Entity("Restoran.Data.Entities.Roller", b =>
                {
                    b.Property<int>("RolId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("RolID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RolId"));

                    b.Property<string>("RolAdi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool?>("RolDurumu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.HasKey("RolId")
                        .HasName("PK__Roller__F92302D1B3A8BA87");

                    b.ToTable("Roller", (string)null);
                });

            modelBuilder.Entity("Restoran.Data.Entities.SiparisDetay", b =>
                {
                    b.Property<int>("SiparisDetayId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("SiparisDetayID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SiparisDetayId"));

                    b.Property<int>("Adet")
                        .HasColumnType("int");

                    b.Property<decimal>("BirimFiyat")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("DetayNot")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SiparisId")
                        .HasColumnType("int")
                        .HasColumnName("SiparisID");

                    b.Property<int>("UrunId")
                        .HasColumnType("int")
                        .HasColumnName("UrunID");

                    b.HasKey("SiparisDetayId")
                        .HasName("PK__SiparisD__DA4BD83290A9C705");

                    b.HasIndex("SiparisId");

                    b.HasIndex("UrunId");

                    b.ToTable("SiparisDetay", (string)null);
                });

            modelBuilder.Entity("Restoran.Data.Entities.Siparisler", b =>
                {
                    b.Property<int>("SiparisId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("SiparisID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SiparisId"));

                    b.Property<int?>("MasaId")
                        .HasColumnType("int")
                        .HasColumnName("MasaID");

                    b.Property<int?>("PersonelId")
                        .HasColumnType("int")
                        .HasColumnName("PersonelID");

                    b.Property<string>("SiparisDurumu")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("SiparisTarihi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("SiparisTipi")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal?>("ToplamTutar")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(10, 2)")
                        .HasDefaultValue(0m);

                    b.Property<int?>("UyeId")
                        .HasColumnType("int")
                        .HasColumnName("UyeID");

                    b.HasKey("SiparisId")
                        .HasName("PK__Siparisl__C3F03BDD36366D4C");

                    b.HasIndex("MasaId");

                    b.HasIndex("PersonelId");

                    b.HasIndex("UyeId");

                    b.ToTable("Siparisler", (string)null);
                });

            modelBuilder.Entity("Restoran.Data.Entities.StokHareket", b =>
                {
                    b.Property<int>("StokHareketId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("StokHareketID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StokHareketId"));

                    b.Property<string>("IsleminAciklamasi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("IsleminTarihSaati")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("PersonelId")
                        .HasColumnType("int")
                        .HasColumnName("PersonelID");

                    b.Property<string>("StokIslemTipi")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("StokMiktari")
                        .HasColumnType("int");

                    b.Property<int?>("UrunId")
                        .HasColumnType("int")
                        .HasColumnName("UrunID");

                    b.HasKey("StokHareketId")
                        .HasName("PK__StokHare__8F9B28C09F5FBF46");

                    b.HasIndex("PersonelId");

                    b.HasIndex("UrunId");

                    b.ToTable("StokHareket", (string)null);
                });

            modelBuilder.Entity("Restoran.Data.Entities.UrunRecetesi", b =>
                {
                    b.Property<int>("ReceteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ReceteID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReceteId"));

                    b.Property<decimal>("KullanimMiktari")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int>("MalzemeId")
                        .HasColumnType("int")
                        .HasColumnName("MalzemeID");

                    b.Property<int>("UrunId")
                        .HasColumnType("int")
                        .HasColumnName("UrunID");

                    b.HasKey("ReceteId")
                        .HasName("PK__Urun_Rec__02D0477B61F5DE92");

                    b.HasIndex("MalzemeId");

                    b.HasIndex("UrunId");

                    b.ToTable("Urun_Recetesi", (string)null);
                });

            modelBuilder.Entity("Restoran.Data.Entities.Urunler", b =>
                {
                    b.Property<int>("UrunId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("UrunID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UrunId"));

                    b.Property<string>("Aciklamalar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Fiyat")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int?>("KategoriId")
                        .HasColumnType("int")
                        .HasColumnName("KategoriID");

                    b.Property<DateTime?>("SilinmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int?>("StokMiktari")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("UrunAdi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("UrunId")
                        .HasName("PK__Urunler__623D364BF036AED3");

                    b.HasIndex("KategoriId");

                    b.ToTable("Urunler", (string)null);
                });

            modelBuilder.Entity("Restoran.Data.Entities.Uyeler", b =>
                {
                    b.Property<int>("UyeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("UyeID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UyeId"));

                    b.Property<string>("Cinsiyet")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("KayitTarihi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("UyeAdi")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UyeEmail")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UyeSifre")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("UyeSoyadi")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UyeTelefon")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("UyeId")
                        .HasName("PK__Uyeler__76F7D9EFEB6A17E3");

                    b.ToTable("Uyeler", (string)null);
                });

            modelBuilder.Entity("Restoran.Data.Entities.Adres", b =>
                {
                    b.HasOne("Restoran.Data.Entities.Uyeler", "Uye")
                        .WithMany("Adres")
                        .HasForeignKey("UyeId")
                        .HasConstraintName("FK_Adres_Uyeler");

                    b.Navigation("Uye");
                });

            modelBuilder.Entity("Restoran.Data.Entities.Iade", b =>
                {
                    b.HasOne("Restoran.Data.Entities.Personel", "Personel")
                        .WithMany("Iades")
                        .HasForeignKey("PersonelId")
                        .HasConstraintName("FK_Iade_Personel");

                    b.HasOne("Restoran.Data.Entities.SiparisDetay", "SiparisDetay")
                        .WithMany("Iades")
                        .HasForeignKey("SiparisDetayId")
                        .HasConstraintName("FK_Iade_SiparisDetay");

                    b.HasOne("Restoran.Data.Entities.Urunler", "Urun")
                        .WithMany("Iades")
                        .HasForeignKey("UrunId")
                        .HasConstraintName("FK_Iade_Urunler");

                    b.Navigation("Personel");

                    b.Navigation("SiparisDetay");

                    b.Navigation("Urun");
                });

            modelBuilder.Entity("Restoran.Data.Entities.Kasa", b =>
                {
                    b.HasOne("Restoran.Data.Entities.Personel", "Personel")
                        .WithMany("Kasas")
                        .HasForeignKey("PersonelId")
                        .HasConstraintName("FK_Kasa_Personel");

                    b.Navigation("Personel");
                });

            modelBuilder.Entity("Restoran.Data.Entities.MalzemeTalep", b =>
                {
                    b.HasOne("Restoran.Data.Entities.Malzemeler", "Malzeme")
                        .WithMany()
                        .HasForeignKey("MalzemeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Malzeme");
                });

            modelBuilder.Entity("Restoran.Data.Entities.Odeme", b =>
                {
                    b.HasOne("Restoran.Data.Entities.Kasa", "Kasa")
                        .WithMany("Odemes")
                        .HasForeignKey("KasaId")
                        .HasConstraintName("FK_Odeme_Kasa");

                    b.HasOne("Restoran.Data.Entities.Personel", "Personel")
                        .WithMany("Odemes")
                        .HasForeignKey("PersonelId")
                        .HasConstraintName("FK_Odeme_Personel");

                    b.HasOne("Restoran.Data.Entities.Siparisler", "Siparis")
                        .WithMany("Odemes")
                        .HasForeignKey("SiparisId")
                        .HasConstraintName("FK_Odeme_Siparisler");

                    b.Navigation("Kasa");

                    b.Navigation("Personel");

                    b.Navigation("Siparis");
                });

            modelBuilder.Entity("Restoran.Data.Entities.Personel", b =>
                {
                    b.HasOne("Restoran.Data.Entities.Roller", "Rol")
                        .WithMany("Personels")
                        .HasForeignKey("RolId")
                        .HasConstraintName("FK_Personel_Roller");

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("Restoran.Data.Entities.PersonelIzin", b =>
                {
                    b.HasOne("Restoran.Data.Entities.Personel", "Personel")
                        .WithMany("PersonelIzins")
                        .HasForeignKey("PersonelId")
                        .HasConstraintName("FK_PersonelIzin_Personel");

                    b.Navigation("Personel");
                });

            modelBuilder.Entity("Restoran.Data.Entities.Rezervasyon", b =>
                {
                    b.HasOne("Restoran.Data.Entities.Masa", "Masa")
                        .WithMany("Rezervasyons")
                        .HasForeignKey("MasaId")
                        .IsRequired()
                        .HasConstraintName("FK_Rezervasyon_Masa");

                    b.HasOne("Restoran.Data.Entities.Uyeler", "Uye")
                        .WithMany()
                        .HasForeignKey("UyeId")
                        .HasConstraintName("FK_Rezervasyon_Uyeler");

                    b.Navigation("Masa");

                    b.Navigation("Uye");
                });

            modelBuilder.Entity("Restoran.Data.Entities.SiparisDetay", b =>
                {
                    b.HasOne("Restoran.Data.Entities.Siparisler", "Siparis")
                        .WithMany("SiparisDetays")
                        .HasForeignKey("SiparisId")
                        .IsRequired()
                        .HasConstraintName("FK_SiparisDetay_Siparisler");

                    b.HasOne("Restoran.Data.Entities.Urunler", "Urun")
                        .WithMany("SiparisDetays")
                        .HasForeignKey("UrunId")
                        .IsRequired()
                        .HasConstraintName("FK_SiparisDetay_Urunler");

                    b.Navigation("Siparis");

                    b.Navigation("Urun");
                });

            modelBuilder.Entity("Restoran.Data.Entities.Siparisler", b =>
                {
                    b.HasOne("Restoran.Data.Entities.Masa", "Masa")
                        .WithMany("Siparislers")
                        .HasForeignKey("MasaId")
                        .HasConstraintName("FK_Siparisler_Masa");

                    b.HasOne("Restoran.Data.Entities.Personel", "Personel")
                        .WithMany("Siparislers")
                        .HasForeignKey("PersonelId")
                        .HasConstraintName("FK_Siparisler_Personel");

                    b.HasOne("Restoran.Data.Entities.Uyeler", "Uye")
                        .WithMany("Siparislers")
                        .HasForeignKey("UyeId")
                        .HasConstraintName("FK_Siparisler_Uyeler");

                    b.Navigation("Masa");

                    b.Navigation("Personel");

                    b.Navigation("Uye");
                });

            modelBuilder.Entity("Restoran.Data.Entities.StokHareket", b =>
                {
                    b.HasOne("Restoran.Data.Entities.Personel", "Personel")
                        .WithMany("StokHarekets")
                        .HasForeignKey("PersonelId")
                        .HasConstraintName("FK_StokHareket_Personel");

                    b.HasOne("Restoran.Data.Entities.Urunler", "Urun")
                        .WithMany("StokHarekets")
                        .HasForeignKey("UrunId")
                        .HasConstraintName("FK_StokHareket_Urunler");

                    b.Navigation("Personel");

                    b.Navigation("Urun");
                });

            modelBuilder.Entity("Restoran.Data.Entities.UrunRecetesi", b =>
                {
                    b.HasOne("Restoran.Data.Entities.Malzemeler", "Malzeme")
                        .WithMany("UrunRecetesis")
                        .HasForeignKey("MalzemeId")
                        .IsRequired()
                        .HasConstraintName("FK_UrunRecetesi_Malzemeler");

                    b.HasOne("Restoran.Data.Entities.Urunler", "Urun")
                        .WithMany("UrunRecetesis")
                        .HasForeignKey("UrunId")
                        .IsRequired()
                        .HasConstraintName("FK_UrunRecetesi_Urunler");

                    b.Navigation("Malzeme");

                    b.Navigation("Urun");
                });

            modelBuilder.Entity("Restoran.Data.Entities.Urunler", b =>
                {
                    b.HasOne("Restoran.Data.Entities.Kategori", "Kategori")
                        .WithMany("Urunlers")
                        .HasForeignKey("KategoriId")
                        .HasConstraintName("FK_Urunler_Kategori");

                    b.Navigation("Kategori");
                });

            modelBuilder.Entity("Restoran.Data.Entities.Kasa", b =>
                {
                    b.Navigation("Odemes");
                });

            modelBuilder.Entity("Restoran.Data.Entities.Kategori", b =>
                {
                    b.Navigation("Urunlers");
                });

            modelBuilder.Entity("Restoran.Data.Entities.Malzemeler", b =>
                {
                    b.Navigation("UrunRecetesis");
                });

            modelBuilder.Entity("Restoran.Data.Entities.Masa", b =>
                {
                    b.Navigation("Rezervasyons");

                    b.Navigation("Siparislers");
                });

            modelBuilder.Entity("Restoran.Data.Entities.Personel", b =>
                {
                    b.Navigation("Iades");

                    b.Navigation("Kasas");

                    b.Navigation("Odemes");

                    b.Navigation("PersonelIzins");

                    b.Navigation("Siparislers");

                    b.Navigation("StokHarekets");
                });

            modelBuilder.Entity("Restoran.Data.Entities.Roller", b =>
                {
                    b.Navigation("Personels");
                });

            modelBuilder.Entity("Restoran.Data.Entities.SiparisDetay", b =>
                {
                    b.Navigation("Iades");
                });

            modelBuilder.Entity("Restoran.Data.Entities.Siparisler", b =>
                {
                    b.Navigation("Odemes");

                    b.Navigation("SiparisDetays");
                });

            modelBuilder.Entity("Restoran.Data.Entities.Urunler", b =>
                {
                    b.Navigation("Iades");

                    b.Navigation("SiparisDetays");

                    b.Navigation("StokHarekets");

                    b.Navigation("UrunRecetesis");
                });

            modelBuilder.Entity("Restoran.Data.Entities.Uyeler", b =>
                {
                    b.Navigation("Adres");

                    b.Navigation("Siparislers");
                });
#pragma warning restore 612, 618
        }
    }
}
